<?php
/**
* Profit Peak
*
* @category  Profit Peak
* @package   ProfitPeak_Tracking
* @author    Profit Peak Team <admin@profitpeak.io>
* @copyright Copyright Profit Peak (https://profitpeak.io/)
*/
$modules = $this->getModuleList();
?>

<table cellpadding="10">
	<thead>
		<tr style="border-bottom: 1px solid #000000; border-collapse: separate">
			<td style="font-weight: bold; min-width: 350px;">Modules</td>
			<td style="font-weight: bold; min-width: 100px;">Version</td>
		</tr>
	</thead>
	<tbody>
		<?php foreach($modules as $module): ?>
			<tr>
				<td><?php echo $module['name']; ?></td>
				<td>
					<?php if($module['version'] == 0): ?>
						Not Installed
					<?php else: ?>
						<?php echo $module['version']; ?>
					<?php endif; ?>
				</td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>
